_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.4
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 5
learning_rate:
    value: 0.0001
